#!/bin/bash
# Automatically download the Astronomy Picture of the Day and set it as
#   the wallpaper for your linux system, and keep a local copy if you desire.
#   User can modify paths at top of script to suit personal needs.
#   Feel free to modify this script as you see fit.
#   Seth D. Galitzer, sgsax@ksu.edu

#   Forked from: https://github.com/sgsax/apod-desktop
#   Modified by Joseph Spencer

# directory where picture is saved
imgdir=$HOME/Pictures
# base URL for the APOD website
baseurl=http://apod.nasa.gov/apod/
# base URL plus name of the page where the current picture can be found
sourceurl=${baseurl}astropix.html

tmpfile=/tmp/astropix.html
imgfile=$imgdir/apod.jpg

# attempt to retrieve the astropix page
attemptNum=1
echo getting page ${sourceurl}
wget ${sourceurl} -T 10 -q -O $tmpfile

while [ $? -ne 0 ]; do

    if [ $attemptNum -gt 20 ]; then
        echo "Unable to retrieve page";
        exit 1;
    fi

    let attemptNum++;
    sleep 15;

    echo "Reattempting... (Attempt ${attemptNum})";
    wget ${sourceurl} -T 10 -q -O $tmpfile
done

# extract the image url from the astropix page
echo getting image url
imgurl=`cat $tmpfile | grep -i "img src" | sed -e 's/.*<img src="\(.*\)".*/\1/i'`

# check image exists
if [ "$imgurl" == "" ]; then
    echo "No image today"
    exit 3
else
    # get that image file
    echo getting image ${baseurl}${imgurl}
    wget ${baseurl}${imgurl} -T 10 -q -O $imgfile
    if [ $? -ne 0 ]; then
        echo "Unable to retrieve image"
        exit 2
    else
        xfdesktop -reload
    fi
fi
